package dev.johnoreilly.climatetrace.ui.utils

// ISO 3166-1 alpha-3 → alpha-2. ClimateTrace's v7 API returns alpha-3 only,
// but FlagKit's getFlag() expects alpha-2.
private val alpha3ToAlpha2Map = mapOf(
    "ABW" to "AW", "AFG" to "AF", "AGO" to "AO", "AIA" to "AI", "ALA" to "AX",
    "ALB" to "AL", "AND" to "AD", "ARE" to "AE", "ARG" to "AR", "ARM" to "AM",
    "ASM" to "AS", "ATA" to "AQ", "ATF" to "TF", "ATG" to "AG", "AUS" to "AU",
    "AUT" to "AT", "AZE" to "AZ",
    "BDI" to "BI", "BEL" to "BE", "BEN" to "BJ", "BES" to "BQ", "BFA" to "BF",
    "BGD" to "BD", "BGR" to "BG", "BHR" to "BH", "BHS" to "BS", "BIH" to "BA",
    "BLM" to "BL", "BLR" to "BY", "BLZ" to "BZ", "BMU" to "BM", "BOL" to "BO",
    "BRA" to "BR", "BRB" to "BB", "BRN" to "BN", "BTN" to "BT", "BVT" to "BV",
    "BWA" to "BW",
    "CAF" to "CF", "CAN" to "CA", "CCK" to "CC", "CHE" to "CH", "CHL" to "CL",
    "CHN" to "CN", "CIV" to "CI", "CMR" to "CM", "COD" to "CD", "COG" to "CG",
    "COK" to "CK", "COL" to "CO", "COM" to "KM", "CPV" to "CV", "CRI" to "CR",
    "CUB" to "CU", "CUW" to "CW", "CXR" to "CX", "CYM" to "KY", "CYP" to "CY",
    "CZE" to "CZ",
    "DEU" to "DE", "DJI" to "DJ", "DMA" to "DM", "DNK" to "DK", "DOM" to "DO",
    "DZA" to "DZ",
    "ECU" to "EC", "EGY" to "EG", "ERI" to "ER", "ESH" to "EH", "ESP" to "ES",
    "EST" to "EE", "ETH" to "ET",
    "FIN" to "FI", "FJI" to "FJ", "FLK" to "FK", "FRA" to "FR", "FRO" to "FO",
    "FSM" to "FM",
    "GAB" to "GA", "GBR" to "GB", "GEO" to "GE", "GGY" to "GG", "GHA" to "GH",
    "GIB" to "GI", "GIN" to "GN", "GLP" to "GP", "GMB" to "GM", "GNB" to "GW",
    "GNQ" to "GQ", "GRC" to "GR", "GRD" to "GD", "GRL" to "GL", "GTM" to "GT",
    "GUF" to "GF", "GUM" to "GU", "GUY" to "GY",
    "HKG" to "HK", "HMD" to "HM", "HND" to "HN", "HRV" to "HR", "HTI" to "HT",
    "HUN" to "HU",
    "IDN" to "ID", "IMN" to "IM", "IND" to "IN", "IOT" to "IO", "IRL" to "IE",
    "IRN" to "IR", "IRQ" to "IQ", "ISL" to "IS", "ISR" to "IL", "ITA" to "IT",
    "JAM" to "JM", "JEY" to "JE", "JOR" to "JO", "JPN" to "JP",
    "KAZ" to "KZ", "KEN" to "KE", "KGZ" to "KG", "KHM" to "KH", "KIR" to "KI",
    "KNA" to "KN", "KOR" to "KR", "KWT" to "KW",
    "LAO" to "LA", "LBN" to "LB", "LBR" to "LR", "LBY" to "LY", "LCA" to "LC",
    "LIE" to "LI", "LKA" to "LK", "LSO" to "LS", "LTU" to "LT", "LUX" to "LU",
    "LVA" to "LV",
    "MAC" to "MO", "MAF" to "MF", "MAR" to "MA", "MCO" to "MC", "MDA" to "MD",
    "MDG" to "MG", "MDV" to "MV", "MEX" to "MX", "MHL" to "MH", "MKD" to "MK",
    "MLI" to "ML", "MLT" to "MT", "MMR" to "MM", "MNE" to "ME", "MNG" to "MN",
    "MNP" to "MP", "MOZ" to "MZ", "MRT" to "MR", "MSR" to "MS", "MTQ" to "MQ",
    "MUS" to "MU", "MWI" to "MW", "MYS" to "MY", "MYT" to "YT",
    "NAM" to "NA", "NCL" to "NC", "NER" to "NE", "NFK" to "NF", "NGA" to "NG",
    "NIC" to "NI", "NIU" to "NU", "NLD" to "NL", "NOR" to "NO", "NPL" to "NP",
    "NRU" to "NR", "NZL" to "NZ",
    "OMN" to "OM",
    "PAK" to "PK", "PAN" to "PA", "PCN" to "PN", "PER" to "PE", "PHL" to "PH",
    "PLW" to "PW", "PNG" to "PG", "POL" to "PL", "PRI" to "PR", "PRK" to "KP",
    "PRT" to "PT", "PRY" to "PY", "PSE" to "PS", "PYF" to "PF",
    "QAT" to "QA",
    "REU" to "RE", "ROU" to "RO", "RUS" to "RU", "RWA" to "RW",
    "SAU" to "SA", "SDN" to "SD", "SEN" to "SN", "SGP" to "SG", "SGS" to "GS",
    "SHN" to "SH", "SJM" to "SJ", "SLB" to "SB", "SLE" to "SL", "SLV" to "SV",
    "SMR" to "SM", "SOM" to "SO", "SPM" to "PM", "SRB" to "RS", "SSD" to "SS",
    "STP" to "ST", "SUR" to "SR", "SVK" to "SK", "SVN" to "SI", "SWE" to "SE",
    "SWZ" to "SZ", "SXM" to "SX", "SYC" to "SC", "SYR" to "SY",
    "TCA" to "TC", "TCD" to "TD", "TGO" to "TG", "THA" to "TH", "TJK" to "TJ",
    "TKL" to "TK", "TKM" to "TM", "TLS" to "TL", "TON" to "TO", "TTO" to "TT",
    "TUN" to "TN", "TUR" to "TR", "TUV" to "TV", "TWN" to "TW", "TZA" to "TZ",
    "UGA" to "UG", "UKR" to "UA", "UMI" to "UM", "URY" to "UY", "USA" to "US",
    "UZB" to "UZ",
    "VAT" to "VA", "VCT" to "VC", "VEN" to "VE", "VGB" to "VG", "VIR" to "VI",
    "VNM" to "VN", "VUT" to "VU",
    "WLF" to "WF", "WSM" to "WS",
    "XKX" to "XK",
    "YEM" to "YE",
    "ZAF" to "ZA", "ZMB" to "ZM", "ZWE" to "ZW",
)

fun alpha3ToAlpha2(code: String): String? = alpha3ToAlpha2Map[code.uppercase()]
